---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mosquitto-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - mko.gtrfc.com
  resources:
  - mosquittoes
  - mosquittousers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mko.gtrfc.com
  resources:
  - mosquittoes/finalizers
  - mosquittoes/status
  - mosquittousers/status
  verbs:
  - update
