// Package builder turns a Mosquitto custom resource into the Kubernetes objects
// the operator applies for it.
package builder

import (
	"fmt"
	"strings"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	mkov1 "github.com/guided-traffic/mosquitto-operator/api/v1"
	"github.com/guided-traffic/mosquitto-operator/internal/common"
)

const (
	// MQTTPort is the plain MQTT listener port.
	MQTTPort int32 = 1883
	// MQTTSPort is the MQTT-over-TLS listener port.
	MQTTSPort int32 = 8883

	// MQTTPortName is the named container and Service port for plain MQTT.
	MQTTPortName = "mqtt"
	// MQTTSPortName is the named container and Service port for MQTT over TLS.
	MQTTSPortName = "mqtts"

	// ConfigKey is the ConfigMap key holding the generated broker configuration.
	ConfigKey = "mosquitto.conf"

	// ConfigMountPath is where the generated configuration is mounted.
	ConfigMountPath = "/mosquitto/config"
	// TLSMountPath is where the referenced TLS secret is mounted.
	TLSMountPath = "/mosquitto/tls"
	// DataMountPath is the broker persistence directory.
	DataMountPath = "/mosquitto/data"

	// TLSCertKey is the secret key holding the server certificate. Together with
	// TLSKeyKey it is the layout cert-manager writes, so a Certificate resource
	// can be pointed at the broker without a copy step.
	TLSCertKey = "tls.crt"
	// TLSKeyKey is the secret key holding the private key.
	TLSKeyKey = "tls.key"
)

// ConfigMapName returns the name of the ConfigMap holding the generated
// broker configuration.
func ConfigMapName(m *mkov1.Mosquitto) string {
	return fmt.Sprintf("%s-config", m.Name)
}

// BrokerPort returns the port the broker listens on: MQTTS when a TLS secret is
// referenced, plain MQTT otherwise. The generated block declares exactly one
// listener either way, so enabling TLS moves that listener rather than adding to
// it. It says nothing about the file as a whole: spec.config is appended after
// the generated block and can declare further listeners, which the operator
// neither models nor exposes as a container or Service port.
func BrokerPort(m *mkov1.Mosquitto) int32 {
	if m.IsTLSEnabled() {
		return MQTTSPort
	}
	return MQTTPort
}

// BrokerPortName returns the named port matching BrokerPort.
func BrokerPortName(m *mkov1.Mosquitto) string {
	if m.IsTLSEnabled() {
		return MQTTSPortName
	}
	return MQTTPortName
}

// GenerateMosquittoConf renders the mosquitto.conf the broker pods run.
//
// Everything stated here describes the generated block only. spec.config is
// appended after it and is not parsed by this operator, so the rendered file can
// carry listeners, bridges or log destinations that none of this accounts for.
//
// Security note on allow_anonymous: Mosquitto 2.x defaults it to false, which
// makes a broker with a listener but no configured authentication reject every
// client. This API has no authentication field, so the generated configuration
// opts in to anonymous access explicitly — otherwise the default resource would
// serve nobody. The exposure is bounded by the ClusterIP Service (no external
// address is created) and by spec.config, which is appended last: a later
// allow_anonymous wins over this one, and on the pinned 2.1 image the way to add
// real authentication is the password-file or acl-file plugin, since the
// password_file and acl_file options are deprecated there and removed in 3.0.
func GenerateMosquittoConf(m *mkov1.Mosquitto) string {
	lines := []string{
		"# Generated by mosquitto-operator. Edits are overwritten on the next reconcile;",
		"# append your own directives through spec.config instead.",
		"",
		"# Logging goes to the container log so kubectl logs is the single source.",
		"log_dest stdout",
		"log_type error",
		"log_type warning",
		"log_type notice",
		"log_type information",
		"",
		"# Persistence writes into the data mount, which is a PVC when spec.storage",
		"# is set and an emptyDir otherwise.",
		"persistence true",
		fmt.Sprintf("persistence_location %s/", DataMountPath),
		"",
	}

	if m.IsTLSEnabled() {
		lines = append(lines,
			"# MQTTS listener. The certificate and key come from the secret named in",
			"# spec.tls.secretName; the operator neither creates nor renews them.",
			fmt.Sprintf("listener %d", MQTTSPort),
			fmt.Sprintf("certfile %s/%s", TLSMountPath, TLSCertKey),
			fmt.Sprintf("keyfile %s/%s", TLSMountPath, TLSKeyKey),
			"",
		)
	} else {
		lines = append(lines,
			"# Plain MQTT listener.",
			fmt.Sprintf("listener %d", MQTTPort),
			"",
		)
	}

	lines = append(lines,
		"# This broker accepts anonymous clients: the CRD models no authentication,",
		"# and Mosquitto 2.x would otherwise reject every client. Anything that can",
		"# route to the ClusterIP Service can publish and subscribe. To change that,",
		"# configure the password-file or acl-file plugin through spec.config, which",
		"# is appended below this line.",
		"allow_anonymous true",
		"",
	)

	if strings.TrimSpace(m.Spec.Config) != "" {
		lines = append(lines,
			"# spec.config, appended verbatim.",
			strings.TrimRight(m.Spec.Config, "\n"),
			"",
		)
	}

	return strings.Join(lines, "\n")
}

// BuildConfigMap builds the ConfigMap carrying the generated broker configuration.
func BuildConfigMap(m *mkov1.Mosquitto) *corev1.ConfigMap {
	return &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      ConfigMapName(m),
			Namespace: m.Namespace,
			Labels:    common.BaseLabels(m, ResolveImage(m)),
		},
		Data: map[string]string{
			ConfigKey: GenerateMosquittoConf(m),
		},
	}
}
