// Package builder turns a Mosquitto custom resource into the Kubernetes objects
// the operator applies for it.
package builder

import (
	"fmt"
	"strings"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	mkov1 "github.com/guided-traffic/mosquitto-operator/api/v1"
	"github.com/guided-traffic/mosquitto-operator/internal/common"
)

// SysInterval and MaxPacketSize are the 2.1 defaults the generated file states
// explicitly (ADR 0002 D7): seconds between $SYS updates, and the largest MQTT
// packet in bytes (M29).
const (
	SysInterval   = 10
	MaxPacketSize = 2000000
)

const (
	// MQTTPort is the plain MQTT listener port.
	MQTTPort int32 = 1883
	// MQTTSPort is the MQTT-over-TLS listener port.
	MQTTSPort int32 = 8883

	// MQTTPortName is the named container and Service port for plain MQTT.
	MQTTPortName = "mqtt"
	// MQTTSPortName is the named container and Service port for MQTT over TLS.
	MQTTSPortName = "mqtts"

	// ConfigKey is the ConfigMap key holding the generated broker configuration.
	ConfigKey = "mosquitto.conf"

	// ConfigMountPath is where the generated configuration is mounted.
	ConfigMountPath = "/mosquitto/config"
	// TLSMountPath is where the referenced TLS secret is mounted.
	TLSMountPath = "/mosquitto/tls"
	// DataMountPath is the broker persistence directory.
	DataMountPath = "/mosquitto/data"
	// AuthMountPath is where the broker reads the rendered credentials: the
	// emptyDir the auth-init container and the reloader copy them into, as
	// 1883:1883 mode 0600 (ADR 0014 D4).
	AuthMountPath = "/mosquitto/auth"

	// PasswordPluginPath is the password-file plugin of the pinned image
	// (docs/developer/broker-behaviour.md M1).
	PasswordPluginPath = "/usr/lib/mosquitto_password_file.so" // #nosec G101 -- a plugin path, not a credential
	// ACLPluginPath is the acl-file plugin of the pinned image (M1).
	ACLPluginPath = "/usr/lib/mosquitto_acl_file.so"

	// TLSCertKey is the secret key holding the server certificate. Together with
	// TLSKeyKey it is the layout cert-manager writes, so a Certificate resource
	// can be pointed at the broker without a copy step.
	TLSCertKey = "tls.crt"
	// TLSKeyKey is the secret key holding the private key.
	TLSKeyKey = "tls.key"
)

// ConfigMapName returns the name of the ConfigMap holding the generated
// broker configuration.
func ConfigMapName(m *mkov1.Mosquitto) string {
	return fmt.Sprintf("%s-config", m.Name)
}

// BrokerPort returns the port the broker listens on: MQTTS when a TLS secret is
// referenced, plain MQTT otherwise. The generated block declares exactly one
// listener either way, so enabling TLS moves that listener rather than adding to
// it. It says nothing about the file as a whole: spec.config is appended after
// the generated block and can declare further listeners, which the operator
// neither models nor exposes as a container or Service port.
func BrokerPort(m *mkov1.Mosquitto) int32 {
	if m.IsTLSEnabled() {
		return MQTTSPort
	}
	return MQTTPort
}

// BrokerPortName returns the named port matching BrokerPort.
func BrokerPortName(m *mkov1.Mosquitto) string {
	if m.IsTLSEnabled() {
		return MQTTSPortName
	}
	return MQTTPortName
}

// GenerateMosquittoConf renders the mosquitto.conf the broker pods run.
//
// The broker requires a login on its one listener and accepts nobody else
// (ADR 0008 D13): the password-file and acl-file plugins read the files the
// operator renders from the MosquittoUser objects bound to the broker, and
// listener_allow_anonymous is false. use_username_as_clientid makes the client
// ID the username, so no client can take over another's session (D14).
// spec.config is appended last, and only after ValidateSpecConfig accepted every
// line of it (D15), so it can tune the broker but not open a second listener,
// load a plugin or turn anonymous access back on.
func GenerateMosquittoConf(m *mkov1.Mosquitto) string {
	lines := []string{
		"# Generated by mosquitto-operator. Edits are overwritten on the next reconcile;",
		"# append your own directives through spec.config instead.",
		"",
		"# Logging goes to the container log so kubectl logs is the single source.",
		"log_dest stdout",
		"log_type error",
		"log_type warning",
		"log_type notice",
		"log_type information",
		"",
		"# Persistence writes into the data mount, which is a PVC when spec.storage",
		"# is set and an emptyDir otherwise.",
		"persistence true",
		fmt.Sprintf("persistence_location %s/", DataMountPath),
		"",
		"# Two broker defaults, stated rather than inherited (M28, M29): how often",
		"# $SYS is published, which is the resolution of the metrics exporter, and",
		"# the packet limit 2.1 lowered. A line in spec.config overrides either.",
		fmt.Sprintf("sys_interval %d", SysInterval),
		fmt.Sprintf("max_packet_size %d", MaxPacketSize),
		"",
		"# Users. The operator renders every MosquittoUser bound to this broker into",
		"# these two files; the reloader sidecar copies a change in and reloads the",
		"# broker without a restart. There is no anonymous access.",
		"plugin_load pwfile " + PasswordPluginPath,
		fmt.Sprintf("plugin_opt_password_file %s/passwd", AuthMountPath),
		"plugin_load aclfile " + ACLPluginPath,
		fmt.Sprintf("plugin_opt_acl_file %s/acl", AuthMountPath),
		"",
	}

	if m.IsTLSEnabled() {
		lines = append(lines,
			"# MQTTS listener. The certificate and key come from the secret named in",
			"# spec.tls.secretName; the operator neither creates nor renews them.",
			fmt.Sprintf("listener %d", MQTTSPort),
			fmt.Sprintf("certfile %s/%s", TLSMountPath, TLSCertKey),
			fmt.Sprintf("keyfile %s/%s", TLSMountPath, TLSKeyKey),
		)
	} else {
		lines = append(lines,
			"# Plain MQTT listener.",
			fmt.Sprintf("listener %d", MQTTPort),
		)
	}

	lines = append(lines,
		"listener_allow_anonymous false",
		"# The client ID is the username: no client can take over another client's",
		"# session, and one username holds one connection.",
		"use_username_as_clientid true",
		"plugin_use pwfile",
		"plugin_use aclfile",
		"",
	)

	if strings.TrimSpace(m.Spec.Config) != "" {
		lines = append(lines,
			"# spec.config, appended after every line passed the allowlist.",
			strings.TrimRight(m.Spec.Config, "\n"),
			"",
		)
	}

	return strings.Join(lines, "\n")
}

// BuildConfigMap builds the ConfigMap carrying the generated broker configuration.
func BuildConfigMap(m *mkov1.Mosquitto) *corev1.ConfigMap {
	return &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      ConfigMapName(m),
			Namespace: m.Namespace,
			Labels:    common.BaseLabels(m, ResolveImage(m)),
		},
		Data: map[string]string{
			ConfigKey: GenerateMosquittoConf(m),
		},
	}
}
